const booksData = [
  // ==========================================
  // 1ST YEAR (SEMESTER 1 & 2 - ALL BRANCHES COMMON)
  // ==========================================
  {
    bookId: 'BK-1001',
    isbn: '978-8189757618',
    title: 'Engineering Physics',
    author: 'Gaur & Gupta',
    category: '1st Year (Common)',
    publisher: 'Dhanpat Rai Publications',
    publicationYear: 2021,
    description: 'Standard prescribed textbook for Engineering Physics covering Optics, Laser & Fiber Optics, Quantum Mechanics, Solid State Physics, and Electromagnetic Field Theory.',
    totalCopies: 15,
    availableCopies: 15,
    shelfNumber: 'Rack 1YR-A1',
    coverImage: '/books/engineering_physics.jpg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1002',
    isbn: '978-8174091955',
    title: 'Engineering Mathematics-I',
    author: 'B.S. Grewal',
    category: '1st Year (Common)',
    publisher: 'Khanna Publishers',
    publicationYear: 2022,
    description: 'Essential foundation textbook for 1st Year Engineering Mathematics covering Matrices, Differential Calculus, Partial Differentiation, Multiple Integrals, and Vector Calculus.',
    totalCopies: 20,
    availableCopies: 20,
    shelfNumber: 'Rack 1YR-A2',
    coverImage: '/books/engineering_math_1.jpg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1003',
    isbn: '978-8121924405',
    title: 'Fundamentals of Electrical Engineering',
    author: 'V.K. Mehta',
    category: '1st Year (Common)',
    publisher: 'S. Chand Publishing',
    publicationYear: 2020,
    description: 'Comprehensive textbook covering DC Circuits, AC Fundamentals, Transformers, Electrical Machines, and Domestic Electrical Installations.',
    totalCopies: 12,
    availableCopies: 12,
    shelfNumber: 'Rack 1YR-B1',
    coverImage: '/books/electrical_engineering.jpg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1004',
    isbn: '978-9353165130',
    title: 'Programming for Problem Solving',
    author: 'E. Balagurusamy',
    category: '1st Year (Common)',
    publisher: 'McGraw Hill Education',
    publicationYear: 2021,
    description: 'Core first-year computer programming text in ANSI C covering Algorithms, Flowcharts, Conditional Loops, Arrays, Strings, Functions, Pointers, Structures, and File Handling.',
    totalCopies: 18,
    availableCopies: 18,
    shelfNumber: 'Rack 1YR-B2',
    coverImage: '/books/programming_c.jpg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1005',
    isbn: '978-0199459759',
    title: 'Environment & Ecology',
    author: 'R. Rajagopalan',
    category: '1st Year (Common)',
    publisher: 'Oxford University Press',
    publicationYear: 2021,
    description: 'Authoritative guide to Environmental Studies, Ecosystem Dynamics, Biodiversity Conservation, Pollution Control, Sustainable Development, and Climate Change Policies.',
    totalCopies: 10,
    availableCopies: 10,
    shelfNumber: 'Rack 1YR-C1',
    coverImage: '/books/environment_ecology.jpg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1006',
    isbn: '978-8187433170',
    title: 'Engineering Chemistry',
    author: 'Jain & Jain',
    category: '1st Year (Common)',
    publisher: 'Dhanpat Rai Publishing',
    publicationYear: 2021,
    description: 'Comprehensive engineering chemistry book covering Water Treatment, Polymers, Lubricants, Corrosion Control, Electrochemistry, Spectroscopy, and Green Chemistry.',
    totalCopies: 14,
    availableCopies: 14,
    shelfNumber: 'Rack 1YR-C2',
    coverImage: '/books/engineering_chemistry.jpg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1007',
    isbn: '978-8174091962',
    title: 'Engineering Mathematics-II',
    author: 'B.S. Grewal',
    category: '1st Year (Common)',
    publisher: 'Khanna Publishers',
    publicationYear: 2022,
    description: 'Standard 2nd Semester textbook covering Ordinary & Partial Differential Equations, Laplace Transforms, Fourier Series, and Complex Analysis.',
    totalCopies: 18,
    availableCopies: 18,
    shelfNumber: 'Rack 1YR-D1',
    coverImage: '/books/engineering_math_2.jpg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1008',
    isbn: '978-0195693409',
    title: 'Fundamentals of Electronics Engineering',
    author: 'David A. Bell',
    category: '1st Year (Common)',
    publisher: 'Oxford University Press',
    publicationYear: 2020,
    description: 'Introductory electronics textbook covering Semiconductor Diodes, BJT & MOSFET Transistors, Operational Amplifiers (Op-Amps), Oscillators, and Digital Logic Circuits.',
    totalCopies: 12,
    availableCopies: 12,
    shelfNumber: 'Rack 1YR-D2',
    coverImage: '/books/electronics_engineering.jpg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1009',
    isbn: '978-9380804361',
    title: 'Fundamentals of Mechanical Engineering',
    author: 'R.K. Rajput',
    category: '1st Year (Common)',
    publisher: 'Laxmi Publications',
    publicationYear: 2021,
    description: 'First-year mechanical engineering text covering Engineering Mechanics, Thermodynamics, IC Engines, Refrigeration & Air Conditioning, Power Transmission, and Hydraulic Machines.',
    totalCopies: 14,
    availableCopies: 14,
    shelfNumber: 'Rack 1YR-E1',
    coverImage: '/books/mechanical_engineering.jpg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1010',
    isbn: '978-0199457069',
    title: 'Soft Skills',
    author: 'Meenakshi Raman & Sangeeta Sharma',
    category: '1st Year (Common)',
    publisher: 'Oxford University Press',
    publicationYear: 2021,
    description: 'Essential university guide for engineering students covering Professional Communication, Technical Writing, Presentation Skills, Group Discussions, and Interview Etiquette.',
    totalCopies: 16,
    availableCopies: 16,
    shelfNumber: 'Rack 1YR-E2',
    coverImage: '/books/soft_skills.jpg',
    status: 'available',
    timesBorrowed: 0,
  },

  // ==========================================
  // 2ND YEAR (SEMESTER 3 & 4 - CORE CS / IT / EC / ME)
  // ==========================================
  {
    bookId: 'BK-1011',
    isbn: '978-0070601680',
    title: 'Data Structures',
    author: 'Seymour Lipschutz',
    category: 'Computer Science & IT',
    publisher: "McGraw Hill (Schaum's Outlines)",
    publicationYear: 2021,
    description: "Prescribed textbook for Data Structures covering Arrays, Linked Lists, Stacks, Queues, Recursion, Trees, Graphs, Sorting, and Searching Algorithms with complete C implementations.",
    totalCopies: 15,
    availableCopies: 15,
    shelfNumber: 'Rack 2YR-CS01',
    coverImage: '/books/data_structures.jpg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1012',
    isbn: '978-1259005275',
    title: 'Computer Organization & Architecture',
    author: 'V. Carl Hamacher',
    category: 'Computer Science & IT',
    publisher: 'McGraw Hill Education',
    publicationYear: 2021,
    description: 'Core 2nd-year computer architecture textbook covering Basic Processing Units, Pipelining, Memory System Hierarchy, I/O Organization, and Embedded Systems.',
    totalCopies: 14,
    availableCopies: 14,
    shelfNumber: 'Rack 2YR-CS02',
    coverImage: '/books/computer_organization.jpg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1013',
    isbn: '978-0070681880',
    title: 'Discrete Structures & Theory of Logic',
    author: 'Kenneth H. Rosen',
    category: 'Computer Science & IT',
    publisher: 'McGraw Hill Higher Education',
    publicationYear: 2021,
    description: 'Standard prescribed textbook for Discrete Structures & Theory of Logic covering Sets, Relations, Propositional & Predicate Logic, Group Theory, Posets, Lattices, and Boolean Algebra.',
    totalCopies: 16,
    availableCopies: 16,
    shelfNumber: 'Rack 2YR-CS03',
    coverImage: '/books/discrete_structures.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1014',
    isbn: '978-8174091979',
    title: 'Mathematics-IV',
    author: 'B.S. Grewal',
    category: 'Applied Mathematics',
    publisher: 'Khanna Publishers',
    publicationYear: 2022,
    description: 'Prescribed 4th Semester Engineering Mathematics textbook covering Complex Analysis, Contour Integration, Probability Distributions, Sampling Theory, and Statistical Hypothesis Testing.',
    totalCopies: 18,
    availableCopies: 18,
    shelfNumber: 'Rack 2YR-M01',
    coverImage: '/books/mathematics_4.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1015',
    isbn: '978-8187972427',
    title: 'Universal Human Values & Professional Ethics',
    author: 'R.R. Gaur, R. Asthana',
    category: 'Applied Sciences & Humanities',
    publisher: 'Excel Books Publishers',
    publicationYear: 2021,
    description: 'Mandatory course textbook for Universal Human Values and Professional Ethics focusing on self-exploration, harmony in human being, family, society, nature, and ethical professional conduct.',
    totalCopies: 20,
    availableCopies: 20,
    shelfNumber: 'Rack 2YR-HV01',
    coverImage: '/books/human_values.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1016',
    isbn: '978-0199480173',
    title: 'Python Programming',
    author: 'Reema Thareja',
    category: 'Computer Science & IT',
    publisher: 'Oxford University Press',
    publicationYear: 2022,
    description: 'Comprehensive Python programming textbook covering Python Data Types, Control Structures, Functions, Modules, OOPs, Exception Handling, File I/O, NumPy, and GUI Programming with Tkinter.',
    totalCopies: 15,
    availableCopies: 15,
    shelfNumber: 'Rack 2YR-CS04',
    coverImage: '/books/python_programming.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1017',
    isbn: '978-1119456339',
    title: 'Operating System',
    author: 'Abraham Silberschatz, Peter B. Galvin, Greg Gagne',
    category: 'Computer Science & IT',
    publisher: 'Wiley International Edition',
    publicationYear: 2021,
    description: 'The definitive Dinosaur textbook for Operating Systems covering Processes, Threads, CPU Scheduling, Synchronization, Deadlocks, Memory Management, Virtual Memory, and File Systems.',
    totalCopies: 16,
    availableCopies: 16,
    shelfNumber: 'Rack 2YR-CS05',
    coverImage: '/books/operating_systems.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1018',
    isbn: '978-0070660489',
    title: 'Theory of Automata & Formal Languages',
    author: 'John C. Martin',
    category: 'Computer Science & IT',
    publisher: 'McGraw Hill Education',
    publicationYear: 2020,
    description: 'Standard textbook for Formal Languages and Computation Theory covering Deterministic/Non-Deterministic Finite Automata, Regular Expressions, Context-Free Grammars, Pushdown Automata, and Turing Machines.',
    totalCopies: 12,
    availableCopies: 12,
    shelfNumber: 'Rack 2YR-CS06',
    coverImage: '/books/theory_of_automata.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1019',
    isbn: '978-1260440232',
    title: 'Object-Oriented Programming with Java',
    author: 'Herbert Schildt',
    category: 'Computer Science & IT',
    publisher: 'Oracle Press / McGraw Hill',
    publicationYear: 2022,
    description: 'Authoritative Java guide covering Object-Oriented paradigms, Classes, Inheritance, Interfaces, Packages, Exception Handling, Multithreading, Generics, Stream API, and Collections Framework.',
    totalCopies: 15,
    availableCopies: 15,
    shelfNumber: 'Rack 2YR-CS07',
    coverImage: '/books/java_programming.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1020',
    isbn: '978-9332542525',
    title: 'Digital Electronics',
    author: 'M. Morris Mano & Michael D. Ciletti',
    category: 'Electronics & Electrical',
    publisher: 'Pearson Education',
    publicationYear: 2021,
    description: 'Standard reference for Digital Electronics & Logic Design covering Boolean Algebra, Karnaugh Maps, Combinational Circuits, Flip-Flops, Counters, Shift Registers, Memory Units, and Verilog HDL.',
    totalCopies: 14,
    availableCopies: 14,
    shelfNumber: 'Rack 2YR-EC01',
    coverImage: '/books/digital_electronics.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1021',
    isbn: '978-0199457496',
    title: 'Technical Communication',
    author: 'Meenakshi Raman & Sangeeta Sharma',
    category: 'Applied Sciences & Humanities',
    publisher: 'Oxford University Press',
    publicationYear: 2021,
    description: 'Prescribed university textbook for Technical Communication covering Technical Writing, Research Reports, Proposals, Professional Presentations, Group Discussions, and Corporate Communication.',
    totalCopies: 14,
    availableCopies: 14,
    shelfNumber: 'Rack 2YR-HU01',
    coverImage: '/books/technical_communication.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1022',
    isbn: '978-8126521791',
    title: 'Cyber Security',
    author: 'Nina Godbole & Sunit Belapure',
    category: 'Cyber Security & Cloud',
    publisher: 'Wiley India Publishing',
    publicationYear: 2021,
    description: 'Prescribed 2nd-Year course text on Cyber Security covering Cyber Crimes, Information Warfare, Cryptography, Network Security, Cyber Forensics Investigation, and Legal Perspectives under the IT Act.',
    totalCopies: 14,
    availableCopies: 14,
    shelfNumber: 'Rack 2YR-SEC01',
    coverImage: '/books/cyber_security.svg',
    status: 'available',
    timesBorrowed: 0,
  },

  // ==========================================
  // 3RD YEAR (SEMESTER 5 & 6 - CORE CS, IT & SPECIALIZATIONS)
  // ==========================================
  {
    bookId: 'BK-1023',
    isbn: '978-0078022159',
    title: 'Database Management System',
    author: 'Abraham Silberschatz, Henry F. Korth, S. Sudarshan',
    category: 'Computer Science & IT',
    publisher: 'McGraw Hill Education',
    publicationYear: 2021,
    description: 'Core 3rd Year textbook for Database Management Systems (DBMS). Relational Data Model, SQL Queries, Relational Algebra, ER Modeling, Normalization (1NF to BCNF), Indexing (B+ Trees), Transactions, ACID, and Concurrency Control (2PL).',
    totalCopies: 15,
    availableCopies: 15,
    shelfNumber: 'Rack 3YR-CS01',
    coverImage: '/books/database_management_system.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1024',
    isbn: '978-0199457533',
    title: 'Web Technology',
    author: 'Uttam K. Roy',
    category: 'Computer Science & IT',
    publisher: 'Oxford University Press',
    publicationYear: 2021,
    description: 'Comprehensive 3rd Year text for Web Technology covering HTML5, CSS3, JavaScript ES6, XML, AJAX, PHP & MySQL backend, Java Servlets lifecycle, JSP architecture, and RESTful Web Services.',
    totalCopies: 14,
    availableCopies: 14,
    shelfNumber: 'Rack 3YR-CS02',
    coverImage: '/books/web_technology.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1025',
    isbn: '978-0262046305',
    title: 'Design & Analysis of Algorithms',
    author: 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein',
    category: 'Computer Science & IT',
    publisher: 'The MIT Press',
    publicationYear: 2022,
    description: 'Prescribed syllabus standard for Design and Analysis of Algorithms (DAA). Asymptotic analysis, Divide & Conquer, Dynamic Programming, Greedy algorithms, Graph algorithms (Dijkstra, Bellman-Ford, Kruskal), and NP-Completeness.',
    totalCopies: 16,
    availableCopies: 16,
    shelfNumber: 'Rack 3YR-CS03',
    coverImage: '/books/design_and_analysis_of_algorithms.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1026',
    isbn: '978-1259096952',
    title: 'Machine Learning Techniques',
    author: 'Tom M. Mitchell',
    category: 'Artificial Intelligence & Data',
    publisher: 'McGraw Hill Education',
    publicationYear: 2020,
    description: 'Comprehensive 3rd Year curriculum text on Machine Learning Techniques. Concept Learning, Decision Trees (ID3/C4.5), Neural Networks, Bayesian Learning, Support Vector Machines (SVM), Clustering, and Reinforcement Learning.',
    totalCopies: 12,
    availableCopies: 12,
    shelfNumber: 'Rack 3YR-AI01',
    coverImage: '/books/machine_learning_techniques.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1027',
    isbn: '978-9389949186',
    title: 'C++ Programming',
    author: 'E. Balagurusamy',
    category: 'Computer Science & IT',
    publisher: 'McGraw Hill Education',
    publicationYear: 2022,
    description: 'Standard textbook for Object-Oriented Programming with C++. Classes & Objects, Constructors & Destructors, Operator Overloading, Inheritance, Polymorphism, Virtual Functions, Templates, Exception Handling, and STL.',
    totalCopies: 18,
    availableCopies: 18,
    shelfNumber: 'Rack 3YR-CS04',
    coverImage: '/books/cpp_programming.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1028',
    isbn: '978-9389991192',
    title: 'Constitution of India (COI)',
    author: 'Dr. Durga Das Basu (D.D. Basu) & Dr. B.R. Ambedkar',
    category: 'Applied Sciences & Humanities',
    publisher: 'LexisNexis',
    publicationYear: 2021,
    description: 'Mandatory 3rd Year textbook for Constitution of India, Law and Engineering (KNC501/KNC601). The Preamble, Fundamental Rights & Duties, Directive Principles, Parliamentary System, Judiciary, Cyber Law & IPR.',
    totalCopies: 15,
    availableCopies: 15,
    shelfNumber: 'Rack 3YR-GEN01',
    coverImage: '/books/constitution_of_india.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1029',
    isbn: '978-0133943030',
    title: 'Software Engineering',
    author: 'Ian Sommerville',
    category: 'Computer Science & IT',
    publisher: 'Pearson Education',
    publicationYear: 2021,
    description: 'Authoritative 3rd Year text for Software Engineering. Software Process Models, Agile Scrum, Requirements Engineering (SRS), System Modeling & UML Architecture, Software Testing, CI/CD, and Quality Assurance.',
    totalCopies: 14,
    availableCopies: 14,
    shelfNumber: 'Rack 3YR-CS05',
    coverImage: '/books/software_engineering.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1030',
    isbn: '978-0321486813',
    title: 'Compiler Design',
    author: 'Alfred V. Aho, Monica S. Lam, Ravi Sethi, Jeffrey D. Ullman',
    category: 'Computer Science & IT',
    publisher: 'Pearson Education',
    publicationYear: 2020,
    description: 'The definitive Dragon Book for Compiler Design. 6-Phase Compiler Pipeline: Lexical Analysis (Lex/DFA), Syntax Analysis (LL/LR Parsers, Yacc), Semantic Analysis & SDT, Intermediate Code (3AC), DAG Code Optimization, and Code Generation.',
    totalCopies: 12,
    availableCopies: 12,
    shelfNumber: 'Rack 3YR-CS06',
    coverImage: '/books/compiler_design.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1031',
    isbn: '978-0073376226',
    title: 'Computer Networks',
    author: 'Behrouz A. Forouzan',
    category: 'Computer Science & IT',
    publisher: 'McGraw Hill Education',
    publicationYear: 2021,
    description: 'Standard 3rd Year textbook for Computer Networks & Data Communications. 7-Layer OSI and TCP/IP protocol suites, Physical Layer Transmission, Data Link Flow Control (CRC/CSMA), IPv4/IPv6 Addressing, Routing (OSPF/BGP), TCP/UDP, and Security.',
    totalCopies: 15,
    availableCopies: 15,
    shelfNumber: 'Rack 3YR-CS07',
    coverImage: '/books/computer_networks.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1032',
    isbn: '978-8126565078',
    title: 'Big Data',
    author: 'Seema Acharya & Subhashini Chellappan',
    category: 'Artificial Intelligence & Data',
    publisher: 'Wiley India',
    publicationYear: 2021,
    description: 'Prescribed 3rd Year text for Big Data Analytics. 5Vs of Big Data, Hadoop Distributed File System (HDFS), MapReduce Programming, Apache Spark RDDs & DataFrames, Hive QL, Pig, and NoSQL (MongoDB, Cassandra, HBase).',
    totalCopies: 10,
    availableCopies: 10,
    shelfNumber: 'Rack 3YR-AI02',
    coverImage: '/books/big_data.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1033',
    isbn: '978-8120352513',
    title: 'Emerging Information Technology & Knowledge (EITK)',
    author: 'V. Rajaraman & Dr. Sushila Madan',
    category: 'Emerging Technologies',
    publisher: 'PHI Learning',
    publicationYear: 2022,
    description: 'Prescribed curriculum guide for Emerging Information Technology & Knowledge (EITK). Covers Artificial Intelligence, Cloud & Edge Computing, Internet of Things (IoT), Blockchain Distributed Ledgers, Quantum Computing, and Knowledge Systems.',
    totalCopies: 12,
    availableCopies: 12,
    shelfNumber: 'Rack 3YR-EM01',
    coverImage: '/books/eitk.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1034',
    isbn: '978-0077122799',
    title: 'Software Project Management (SPM)',
    author: 'Bob Hughes, Mike Cotterell & Rajib Mall',
    category: 'Computer Science & IT',
    publisher: 'McGraw Hill Education',
    publicationYear: 2021,
    description: 'Prescribed 3rd Year text for Software Project Management (SPM). Project Evaluation, Software Effort Estimation (COCOMO & FPA), Activity Planning (PERT/CPM Networks), Risk Management Matrices, Resource Allocation, and Agile Scrum Monitoring.',
    totalCopies: 12,
    availableCopies: 12,
    shelfNumber: 'Rack 3YR-CS08',
    coverImage: '/books/software_project_management.svg',
    status: 'available',
    timesBorrowed: 0,
  },

  // ==========================================
  // 4TH YEAR (SEMESTER 7 & 8 - CAPSTONE & ADVANCED ELECTIVES)
  // ==========================================
  {
    bookId: 'BK-1035',
    isbn: '978-0262680769',
    title: 'Design Thinking (DT)',
    author: 'Peter G. Rowe',
    category: 'Emerging Technologies',
    publisher: 'The MIT Press',
    publicationYear: 2021,
    description: 'Prescribed 4th Year textbook for Design Thinking (DT / KOE071). 5-Stage Human-Centered Design methodology (Empathize, Define, Ideate, Prototype, Test), Problem Framing, User Persona Research, and Innovation Architecture.',
    totalCopies: 14,
    availableCopies: 14,
    shelfNumber: 'Rack 4YR-DT01',
    coverImage: '/books/design_thinking.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1036',
    isbn: '978-1259029950',
    title: 'Cloud Computing (CC)',
    author: 'Rajkumar Buyya',
    category: 'Cyber Security & Cloud',
    publisher: 'Morgan Kaufmann / McGraw Hill',
    publicationYear: 2021,
    description: 'Prescribed 4th Year textbook for Cloud Computing (CC / KCS071). Virtualization technologies, Cloud service models (IaaS, PaaS, SaaS), Public/Private/Hybrid Cloud architecture, Aneka platform, MapReduce, and SLA management.',
    totalCopies: 12,
    availableCopies: 12,
    shelfNumber: 'Rack 4YR-CL01',
    coverImage: '/books/cloud_computing.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1037',
    isbn: '978-0134610993',
    title: 'Artificial Intelligence (AI)',
    author: 'Stuart Russell, Peter Norvig',
    category: 'Artificial Intelligence & Data',
    publisher: 'Pearson Education',
    publicationYear: 2021,
    description: 'Prescribed 4th Year core textbook for Artificial Intelligence (AI / KCS701). Intelligent Agents, Uninformed & Heuristic Search (A*), Adversarial Game Playing (Minimax, Alpha-Beta), Knowledge Representation, and Inference.',
    totalCopies: 15,
    availableCopies: 15,
    shelfNumber: 'Rack 4YR-AI01',
    coverImage: '/books/artificial_intelligence.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1038',
    isbn: '978-0262035613',
    title: 'Deep Learning',
    author: 'Ian Goodfellow, Yoshua Bengio & Aaron Courville',
    category: 'Artificial Intelligence & Data',
    publisher: 'MIT Press',
    publicationYear: 2019,
    description: 'Core elective textbook for Deep Learning (KCS072). Mathematical foundations, Deep Feedforward Networks, Convolutional Neural Networks (CNNs), Recurrent Neural Networks (RNNs/LSTMs), Autoencoders, and GANs.',
    totalCopies: 8,
    availableCopies: 8,
    shelfNumber: 'Rack 4YR-AI02',
    coverImage: '/books/deep_learning.svg',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1039',
    isbn: '978-8173719547',
    title: 'Internet of Things: A Hands-On Approach',
    author: 'Arshdeep Bahga & Vijay Madisetti',
    category: 'Emerging Technologies',
    publisher: 'Universities Press',
    publicationYear: 2021,
    description: 'AKTU textbook for Internet of Things (IoT - KCS075/KOE075). IoT reference architecture, Sensing protocols (MQTT, CoAP, WebSockets), Raspberry Pi & Arduino interfacing, Python programming, and IoT Cloud platforms.',
    totalCopies: 8,
    availableCopies: 8,
    shelfNumber: 'Rack 4YR-EM01',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=600&auto=format&fit=crop',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1040',
    isbn: '978-8126571891',
    title: 'Cyber Security: Understanding Cyber Crimes, Computer Forensics and Legal Perspectives',
    author: 'Nina Godbole & Sunit Belapure',
    category: 'Cyber Security & Cloud',
    publisher: 'Wiley India',
    publicationYear: 2020,
    description: 'Prescribed AKTU course text for Cyber Security & Digital Forensics (KCS078/KOE078). Cyber attacks, Botnets, Cloud security risks, Digital forensics investigation lifecycle, and the IT Act 2000 provisions.',
    totalCopies: 10,
    availableCopies: 10,
    shelfNumber: 'Rack 4YR-SEC01',
    coverImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1041',
    isbn: '978-9352132485',
    title: 'Hadoop: The Definitive Guide (4th Edition)',
    author: 'Tom White',
    category: 'Artificial Intelligence & Data',
    publisher: "O'Reilly Media / Shroff Publishers",
    publicationYear: 2019,
    description: 'Standard textbook for Big Data Analytics and Hadoop (KCS081). In-depth coverage of Hadoop Distributed File System (HDFS), MapReduce execution model, Apache Spark, Pig, Hive, and HBase integration.',
    totalCopies: 7,
    availableCopies: 7,
    shelfNumber: 'Rack 4YR-AI02',
    coverImage: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?q=80&w=600&auto=format&fit=crop',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1042',
    isbn: '978-9332518414',
    title: 'Speech and Language Processing (3rd Edition)',
    author: 'Daniel Jurafsky & James H. Martin',
    category: 'Artificial Intelligence & Data',
    publisher: 'Pearson Education',
    publicationYear: 2021,
    description: 'Prescribed textbook for Natural Language Processing (NLP - KCS082). Text normalization, N-gram language models, Vector semantics (Word2Vec), POS tagging, Transformer architectures, and Machine Translation.',
    totalCopies: 6,
    availableCopies: 6,
    shelfNumber: 'Rack 4YR-AI03',
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=600&auto=format&fit=crop',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1043',
    isbn: '978-1839213199',
    title: 'Mastering Blockchain: Distributed Ledgers, Smart Contracts and Cryptography',
    author: 'Imran Bashir',
    category: 'Emerging Technologies',
    publisher: 'Packt Publishing',
    publicationYear: 2021,
    description: 'Comprehensive curriculum guide for Blockchain Architecture & Technologies (KCS083). Consensus mechanisms (PoW, PoS), Bitcoin internals, Ethereum Smart Contract programming in Solidity, and Hyperledger Fabric.',
    totalCopies: 7,
    availableCopies: 7,
    shelfNumber: 'Rack 4YR-EM01',
    coverImage: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=600&auto=format&fit=crop',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1044',
    isbn: '978-8126574889',
    title: 'Professional Android App Development & Mobile Computing',
    author: 'Reto Meier & Ian Lake',
    category: 'Computer Science & IT',
    publisher: 'Wrox / Wiley',
    publicationYear: 2020,
    description: 'AKTU syllabus text for Mobile Application Development & Computing (KCS085). Android Studio lifecycle, Activities, Fragments, SQLite/Room databases, Retrofit REST APIs, Services, and Material Design UI.',
    totalCopies: 8,
    availableCopies: 8,
    shelfNumber: 'Rack 4YR-CS01',
    coverImage: 'https://images.unsplash.com/photo-1526498460520-4c246339dccb?q=80&w=600&auto=format&fit=crop',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1045',
    isbn: '978-9352606368',
    title: 'Non-Conventional Energy Resources (3rd Edition)',
    author: 'B.H. Khan',
    category: 'Mechanical & Civil',
    publisher: 'McGraw Hill Education',
    publicationYear: 2020,
    description: 'Prescribed AKTU Open Elective for Renewable Energy Resources (KOE074). Covers Solar Photovoltaics and Thermal energy, Wind Energy conversion systems, Biomass, Geothermal, Ocean Energy, and Fuel Cells.',
    totalCopies: 6,
    availableCopies: 6,
    shelfNumber: 'Rack 4YR-ME01',
    coverImage: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?q=80&w=600&auto=format&fit=crop',
    status: 'available',
    timesBorrowed: 0,
  },
  {
    bookId: 'BK-1046',
    isbn: '978-9353066406',
    title: 'Operations Research: An Introduction (10th Edition)',
    author: 'Hamdy A. Taha',
    category: 'Applied Mathematics',
    publisher: 'Pearson Education',
    publicationYear: 2019,
    description: 'Standard AKTU Open Elective textbook for Operations Research & Optimization (KOE083). Linear Programming (Simplex & Dual Simplex), Transportation & Assignment models, Network models (CPM/PERT), and Queuing theory.',
    totalCopies: 7,
    availableCopies: 7,
    shelfNumber: 'Rack 4YR-MATH01',
    coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop',
    status: 'available',
    timesBorrowed: 0,
  },
];

const studentsData = [
  {
    name: 'Saurabh Sahu',
    email: 'sahu720p@gmail.com',
    password: 'sahu720p',
    role: 'student',
    studentId: 'STU2024001',
    course: 'B.Tech',
    branch: 'Computer Science & Engineering',
    year: '4th Year',
    phone: '+91 98999 12345',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Saurabh',
    status: 'active',
  },
];

module.exports = {
  booksData,
  studentsData,
};

